from aiogram.types import ContentType, Message, InputFile

#Высшая математика
videoIntegral1 = "BAACAgIAAxkBAAIJM2TdUvq1U-g1G_COF43Ot66cgJvfAALGMAACKevoStyZATjyS8SKMAQ"
videoRyadi1 = "BAACAgIAAxkBAAIJOmTdVArd_y6FhzOvTAIMhB6P01QYAALJMAACKevoShZbZH9UE2a5MAQ"
videoDiffuri1 = "BAACAgIAAxkBAAIJPGTdVGLd65BWWXypo24zCQRToa9OAALKMAACKevoSjql-L3-IsaNMAQ"
videoPredeli1 = "BAACAgIAAxkBAAIJPmTdVKLpZlzSgH-cfu3jNKh6bSBPAALLMAACKevoSvCammGbvICIMAQ"
videoIntegral2 = "BAACAgIAAxkBAAIJQGTdVQAB22BmkSgtwGW2M2zNuORCJgACyzkAAry86UqqsL_zLzO3JjAE"
videoRyadi2 = "BAACAgIAAxkBAAIJQmTdVXklH0fIf9b2fyBAxUXo7FcRAALMMAACKevoSj7b7QekbaSbMAQ"
videoDiffuri2 = "BAACAgIAAxkBAAIJRGTdVaW71PQzvhBd3cvHR3PtodSlAALNMAACKevoSqfOIsA4xX_RMAQ"
videoPredeli2 = "BAACAgIAAxkBAAIJRmTdVeHHAAG7w6ca8BtqFaSgZnETlQACzjAAAinr6Erx5SEDFdEFLjAE"

#Физика
videoElectichestvo1 = "BAACAgIAAxkBAAIJ8GTf4LXlZiipdCkk4ftjUyUX2ELuAAKkNQACvI0BS_xU6XacIB0DMAQ"
videoMagnetism1 = "BAACAgIAAxkBAAIJ8mTf4L0gAeE1zU0stOanRQlfqHhpAAKlNQACvI0BS6dincU0CcYdMAQ"
videoMKT1 = "BAACAgIAAxkBAAIJ9GTf4Pmj1GL8sM65ymyCNzZsWCq-AAKmNQACvI0BS_BqS_vQX1utMAQ"
videoKinematika1 = "BAACAgIAAxkBAAIJ9mTf4QMlILS3544m3VZjVXirA5Z1AAKnNQACvI0BS9zzoJoLLE7lMAQ"
videoDinamika1 = "BAACAgIAAxkBAAIJ-GTf4Ry9f3VocJc3mtsMby7jIPDNAAKoNQACvI0BS8mRWlqpacMmMAQ"
videoElectichestvo2 = "BAACAgIAAxkBAAIJ-mTf4ZOWVI1Tq0JQ2sR5O8RXbnkJAAKqNQACvI0BS3eY-iIG2whfMAQ"
videoMagnetism2 = "BAACAgIAAxkBAAIJ_GTf4aBuU6MQxCAjNwgRjiFe6RasAAKrNQACvI0BS1Sk-T-aCKjcMAQ"
videoMKT2 = "BAACAgIAAxkBAAIJ_mTf4dXUqwLvbb4DIGZ5CHoIkPWiAAKsNQACvI0BSw27LrBqBigbMAQ"
videoKinematika2 = "BAACAgIAAxkBAAIKAAFk3-HcMyA4hnWUI2Ud1F1-dGDjlQACrTUAAryNAUt5r0DpRVLpwjAE"
videoDinamika2 = "BAACAgIAAxkBAAIKAmTf4eLBIddePfluFHkDiNAf4djOAAKuNQACvI0BS-3Qk4Il7mztMAQ"

#Программирование (Второе видео нужно выгрузить из вк)
videoC1 = "BAACAgIAAxkBAAIKV2TjE0K3X1gAAefom0oOHKXriiVZaAACujsAAsftGUsYUummKOkQrTAE"
videoC2 = "BAACAgIAAxkBAAIKV2TjE0K3X1gAAefom0oOHKXriiVZaAACujsAAsftGUsYUummKOkQrTAE"

#Линал (Первое видео нужно выгрузить из вк)
videoLinal1 = "BAACAgIAAxkBAAIKdGTjRfK7KgvtExqcu6pOeq8p2qrcAAJgOgACx-0hS2PrKzc8TOZFMAQ"
videoLinal2 = "BAACAgIAAxkBAAIKdGTjRfK7KgvtExqcu6pOeq8p2qrcAAJgOgACx-0hS2PrKzc8TOZFMAQ"

#Тервер
videoTerver1 = "BAACAgIAAxkBAAIKeGTjRhysnKe-UAUDabcMyFbxjK9HAAJhOgACx-0hS0JmIaj8eEmJMAQ"
videoTerver2 = "BAACAgIAAxkBAAIKemTjRmQhKlwO1tHIcqf8NdWCKpODAAJoOgACx-0hS-ZsW5z2C6qrMAQ"

#Матфиз (Единственное видео нужно выгрузить из вк)
videoMatfiz1 = "BAACAgIAAxkBAAIKemTjRmQhKlwO1tHIcqf8NdWCKpODAAJoOgACx-0hS-ZsW5z2C6qrMAQ"

#Химия и органическая химия


#Физхим (Единственное видео нужно выгрузить из вк)

videFizHim = "BAACAgIAAxkBAAIKemTjRmQhKlwO1tHIcqf8NdWCKpODAAJoOgACx-0hS-ZsW5z2C6qrMAQ"

#Экономическое направление